# Generated by Django 4.0.2 on 2022-03-11 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0005_delete_convertedfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='myuploadfile',
        ),
    ]
