# Generated by Django 4.0.2 on 2022-03-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0006_delete_myuploadfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='myuploadfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=255)),
                ('uploaded_file', models.FileField(upload_to='')),
                ('translated_file', models.FileField(upload_to='')),
            ],
        ),
    ]
